name: "Tester"
on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'ditto/**'
      - 'tests/**'
  pull_request:
    branches:
      - rewrite

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1.1.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/cache@v3.0.1
        id: cached-dependecies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Validate pyproject.toml
        run: poetry check
      - name: Install dependencies
        if: steps.cached-dependecies.outputs.cache-hit != 'true'
        run: poetry install
      - name: Test Utility Functions
        run: poetry run pytest
